version: "3.7"

services:
  app:
    build: .
    image: clean
    container_name: clean
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-architecture
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - mongo

  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
